### PR TITLE
Made Compare Button Middle mouse clickable

### PR DESCRIPTION
**Pull request by HumphreyHCB**
An addition to the compare button for benchmarks, which allows you to middle mouse click the button to open the comparison in a new tab.

### CODE REVIEW

**Comment by smarr** [comment]
@HumphreyHCB could you please add a description to the change and why it is made to the initial PR message? Thanks!

**Review by smarr — APPROVED** [review]

**Comment by smarr** [comment]
@HumphreyHCB I was messing a little more with it, sorry...
Instead of heaving to have a separate click handler, it's now using the event to determine the clicked element/link in the list.

Any concerns from your end, or is this ready for merging?

**Comment by HumphreyHCB** [comment]
I have tested it 

no concerns, i think its ready for merging

**Comment by smarr** [comment]
Done, thanks a lot!

**Pull request merged**
